README.md, doc/mellifluous.txt, lua/mellifluous/colors/sets/alduin.lua, lua/mellifluous/colors/sets/mellifluous.lua, lua/mellifluous/colors/sets/mountain.lua, lua/mellifluous/colors/sets/tender.lua, lua/mellifluous/colors/shades.lua, lua/mellifluous/config.lua, lua/mellifluous/highlights/plugins/init.lua, lua/mellifluous/highlights/plugins/treesitter.lua, lua/mellifluous/utils/highlighter.lua
The headings might be a bit controversial, so I'm open to extending the config.
Preview:
This will also affect vimdoc, and, in the future, neorg.
=> feat(highlights): revamp markup headings, links and raw text

lua/mellifluous/highlights/general.lua
As per your suggested [fix](https://github.com/ramojus/mellifluous.nvim/issues/22)
=> highlight: link FoldColumn to LineNr

lua/mellifluous/highlights/plugins/treesitter.lua
The default color for signs in the `:TSModuleInfo` view is very bright and inconsistent with the colorscheme.
_before_
_after_
<details><summary>Outdated screenshot</summary>
<p>
</p>
</details>
=> fix(treesitter): set highlight of TSModuleInfo signs

lua/mellifluous/highlights/general.lua
Neovim declares the core highlight groups `Added`. `Changed` and `Removed`. Those are used in some cases instead of their `Diff*` counterpart, for example while editing Git hunks during a `git add --patch`, or in docs/changelogs, etc.
The current defaults are very bright, and inconsistent with the colorscheme:
After the changes from this PR:
<details><summary>Outdated screenshots</summary>
<p>
</p>
</details>
=> fix(general): set highlight of added/removed/changed

README.md, lua/mellifluous/config.lua, lua/mellifluous/highlights/general.lua, lua/mellifluous/highlights/plugins/neotest.lua
Disclaimer: I have no clue what I'm doing and just pulled bits in from other support files.
Looks decent but I don't know how to remedy the "chicken/egg" scenario involving the background color of signcolumn vs. the background color of the neotest window.
=> feat(highlights): neotest

lua/mellifluous/highlights/general.lua, lua/mellifluous/utils/highlighter.lua
By default, Neovim uses a color to underline LSP diagnostics. The color matches the severity of the diagnostic, and is very useful to be able to quickly identify multiple diagnostic severities appearing on the same line:
The colorscheme currently doesn't color underlined LSP diagnostics. The example below isn't particularly realistic, but I encountered the case multiple times in Go and Rust codebases, and had to jump to each diagnostic individually (or call `vim.diagnostic.open_float()`) to be able to identify their severity:
After the changes from this PR, colored underlines are restored:
=> feat(highlights): colored underlined LSP diagnostics

README.md, lua/mellifluous/config.lua, lua/mellifluous/highlights/plugins/mason.lua
Improves the highlighting of [Mason](https://github.com/williamboman/mason.nvim) windows (a popular installer for external tools such as LSP servers), which is inconsistent with the colorscheme by default.
_before_
_after_
<details><summary>Outdated screenshots</summary>
<p>
</p>
</details>
=> feat(highlights): add mason support

lua/mellifluous/colors/shades.lua
before:
after:
compared to light bg:
Related to #39
=> fix(colors): increase contrast for dark bg layers

lua/mellifluous/color.lua, lua/mellifluous/colors/init.lua, lua/mellifluous/colors/shades.lua, lua/mellifluous/highlights/general.lua, lua/mellifluous/utils/shader.lua
Instead of relying on shade recipes, one can now replicate a shade from any two colors, thus, shade recipes are no longer needed.
=> refactor(colors): simplify creation and replication of shades

lua/mellifluous/highlights/general.lua
This PR ensures that `DiagnosticOk` and its variants use the colorscheme's green color, instead of Neovim's default bright green color.
The `DiagnosticOk` highlight group and its variants do exist in Neovim. [Some plugins](https://github.com/search?q=DiagnosticOk+lang%3Alua&type=code) and even a few core Neovim functionalities rely on them, although they are used more seldom than `Error`, `Warn`, `Info` and `Hint`.
Currently, all these highlight groups have a bright green foreground color by default (`guifg=NvimLightGreen`). This can be observed by opening the help for `hl-DiagnosticOk` and scrolling until `hl-DiagnosticSignOk`.
This can also be observed in the output of the built-in `:checkhealth` command:
=> fix(highlights): use green color for 'Ok' diagnostics

lua/mellifluous/color.lua, lua/mellifluous/highlights/custom_groups.lua, lua/mellifluous/highlights/general.lua, lua/mellifluous/highlights/plugins/indent_blankline.lua, lua/mellifluous/highlights/plugins/lazy.lua, lua/mellifluous/highlights/plugins/mason.lua, lua/mellifluous/highlights/plugins/neo_tree.lua, lua/mellifluous/highlights/plugins/neotest.lua, lua/mellifluous/highlights/plugins/nvim_tree.lua, lua/mellifluous/highlights/plugins/semantic_tokens.lua, lua/mellifluous/highlights/plugins/treesitter.lua, lua/mellifluous/utils/highlighter.lua
Custom highlight groups allow for highlight modules to share common highlight groups that are not defined by neovim.
As a consequence of introducing them, some highlights were revisited and modified slightly, either to share one common style, or simply adhere a little bit better to colorscheme's vision.
There might some highlights I've missed, that could use custom highlight groups. With future PRs, they should be refactored to use custom highlight groups.
=> refactor(highlights): use custom highlight groups

README.md, doc/mellifluous.txt, lua/mellifluous/colors/init.lua, lua/mellifluous/colors/shades.lua
=> feat(colors): allow color overrides to override shades with predefined colors

lua/mellifluous/highlights/plugins/lazy.lua
I've decided to use bg2 for lazy in #37 (instead of `NormalFloat` - bg3) to make the buttons look more pronounced. The design of the buttons has since been generalized to look good in all contexts (#44) and lazy bg became an issue, because it was inconsistent with other plugins without any real reason.
Furthermore, bg2 doesn't respect transparent_background setting, so we should always use `NormalFloat` bg, which respects this setting.
Fix was attempted in #49, but this PR keeps the inconsistency, which I would prefer to get rid of.
Fixes #51.
=> fix(lazy): use NormalFloat bg as bg

lua/mellifluous/config.lua
CLI commands update the config and reload the colorscheme. The problem is that the config gets modified for easier usage on first load of the colorscheme (via [disable_disabled](https://github.com/ramojus/mellifluous.nvim/blob/b18fef92193d341a3252efcd6d92c4ae2257b535/lua/mellifluous/config.lua#L63-L75) function). Because of this, CLI commands work differently from modifying the config directly (e.g. if `:Mellifluous toggle_transparency` command would enable transparency, the suboptions of `transparent_background` would still be disabled from earlier colorscheme load).
This PR preserves default config (with `get_default_config` function) so that it can be recovered whenever user modifies the config with CLI. For this to work, all user config is saved separately between different loads of …
=> fix(config): rebase on default config after changes from CLI

README.md, doc/mellifluous.txt, lua/mellifluous/colors/colorsets/mellifluous.lua
in favor of new color overrides. [Migration](https://github.com/ramojus/mellifluous.nvim/wiki/Migration-from-v0-to-v1-guidelines#removal-of-bg_contrast-option-for-mellifluous-60)
=> chore(mellifluous): remove `bg_contrast` option

lua/mellifluous/colors/colorsets/mellifluous.lua
Fixes #61. The previous version of this if statement would pass for `nil`, when it should only pass for `false`. The value being `nil` is related to https://github.com/ramojus/mellifluous.nvim/commit/f310eb2422dfa72f6d887efc462985bc82503078 not being merged to v1 branch, so that should also be done.
=> fix(mellifluous): check `neutral` option more thoroughly

lua/mellifluous/highlights/plugins/gitsigns.lua
Prompted by https://github.com/ramojus/mellifluous.nvim/discussions/69.
Lot's of currently styled plugins need revisions, especially considering the strictness of the new contribution guidelines...
I'm assuming there is a gitsigns bug on the second screenshot, where the changed word is not highlighted in green? The same word is highlighted in green on the first screenshot.
=> feat(gitsigns): improve change preview

lua/mellifluous/highlights/general.lua
Prompted by https://github.com/ramojus/mellifluous.nvim/discussions/69
Just aligned it more with how every other element in the colorscheme is colored -- `colors.bg3` as a background for floating window, `custom_groups.MenuButtonSelected` background as a background for the selected item.
=> fix(highlights): improve `Pmenu` readability

lua/mellifluous/colors/init.lua, lua/mellifluous/config.lua
The background usually becomes lighter when transparent background is enabled. This was noticed and discussed [here](https://github.com/ramojus/mellifluous.nvim/pull/50#issuecomment-2259996719)
The default here is something that works relatively well for the types of wallpapers that I use, while still preserving the style and readability of the colorset quite well.
=> feat(config): add lightness option for transparent bg

README.md, doc/mellifluous.txt, lua/mellifluous/config.lua, lua/mellifluous/default_config.lua
The default config that is shown in the documentation has become stale. To solve this problem, only one source for default config will be used.
=> refactor(config): extract default config for easier documentation

lua/mellifluous/highlights/custom_groups.lua, lua/mellifluous/highlights/plugins/fzf.lua
There is some kind of bug where if I switch colorset via CLI, it will not apply backdrop to background. That is fixed when `FzfLuaBackdrop` group is set explicitly. I used this opportunity to customize the backdrop as well.
Something should be done about `lazy` backdrop as well (so it matches this backdrop), but `lazy` does not have a highlight group for this. Should we start modifying plugin configs? It would definitely allow for a more uniform UI, but might be a bit of an overtake.
=> fix(fzf-lua): respect flat background config and set backdrop

README.md, lua/mellifluous/default_config.lua, lua/mellifluous/highlights/plugins/dap_ui.lua
This PR adds initial customizations for the nvim-dap-ui plugin.
The plugin supports several widgets, however I decided to focus my efforts only on the _Control Panel_ in this PR, to keep the scope small and because it is the only widget which looks broken out of the box. The reason being that nvim-dap-ui assumes that the `WinBar` highlight group has a **concrete** background color set, whereas the group is a link in mellifluous.
- https://github.com/rcarriga/nvim-dap-ui/blob/v4.0.0/lua/dapui/config/highlights.lua#L76-L77
- https://github.com/rcarriga/nvim-dap-ui/blob/v4.0.0/lua/dapui/controls.lua#L19-L27
Before:
After:
<details><summary>Outdated screenshots</summary>
<p>
</p>
</details>
=> Add support for nvim-dap-ui controls

lua/mellifluous/highlights/plugins/semantic_tokens.lua
It was one of my core principles when designing this colorscheme, that even macros, for simplicity, should still look like a function - they are usually differentiated syntactically anyways.
=> fix(highlights): link `@lsp.type.macro` to `Macro`
